### PR TITLE
Media Extended v3

### PR DESCRIPTION
**Pull request by aidenlx**
- [ ] replace plyr with custom player
    - [x] subtitle support
    - [x] YouTube support
    - [ ] vimeo support
    - [x] bilibili support
        - [ ] https://github.com/the1812/Bilibili-Evolved/blob/master/CONTRIBUTING.md
        - [ ] convert short url in clipboard to full url (provide option, maybe with Vercel?): https://github.com/aidenlx/mx-bili-plugin/issues/6
            - [ ] show progress bar if timeout
    - [x] extendable API to handle more video hosts
        - [ ] save scripts to indexeddb?
    - [x] webdav support
      - [ ] simple encrypt (token in localstorage encrypted passwords in setting)
      - [ ] Warning about the security risk that other plugin can potentially steal authentication token in logged-in website
    - [ ] onedrive support
    - [ ] poster and placeholder support
    - [ ] ui design
        - [x] basic controls
        - [ ] class indicating media state
        - [ ] alternative ui mode if using remote player's ui
        - [ ] show current playback rate on button?
        - [ ] optimized audio controls
        - [ ] dynamic controls: show/hide on resize
    - [ ] mobile support (deal with electron/node api)
    - [x] filter support: rotate/grayscale...
    - [ ] thumbnail support
    - [ ] keyboard control
        - [x] basic support
        - [ ] visual feedback about current value (speed, volume,...)
        - [ ] improve handling of long press navigate instead of frequently triggering manual seek
        - [ ] fix rename with space/c... not working properly in media view
    - [x] event system? 
        - https://github.com/Chimeejs/chimee/blob/master/doc/zh-cn/design/why-chimee-is-a-frame.md
        - [vidstack](https://www.vidstack.io/docs/player/getting-started/events)
        - https://www.npmjs.com/package/nanoevents
        - action with prop `$MEDIA_CONTROL`, handle them in middleware
        - [ ] dedicated store for YouTube api state
- [ ] proper history support
    - [ ] memorize last media link timestamp (make it compatible with pane relief)
    - [x] memorize playback progress
- [ ] wasm (host in pwa, cache managed by service worker, comm via postMessage)
    - [ ] video ocr via https://github.com/naptha/tesseract.js (create another plugin and use its API)
        - [ ] preprocess image
        - [ ] 临时编辑器（简单处理列表等）
    - [ ] video thumbnails generation
        - https://w3c.github.io/webcodecs/samples/
- [ ] live preview support
    - [x] link handler (open in media view)
    - [x] internal media embed
    - [x] external media mebed
    - [ ] hover preview on external link
    - [ ] fix no source path error
- [ ] media view improvement
    - [x] improve editor-view linking
    - [ ] dedicated window (desktop only)
        - [x] platform-agnostic redux store
        - [x] platform-agnostic react component
        - [ ] key scope management
    - [ ] screenshot
        - [x] basic support
        - [ ] support simple process (crop, rotate, [filter](https://developer.mozilla.org/zh-CN/docs/Web/API/CanvasRenderingContext2D/filter)...)
        - [ ] support copy to clipboard
- [ ] webview player
    - [x] `WebView` component
    - [x] basic bilibili player
    - [x] login page for given website
- [ ] timestamp link improvement 
    - [ ] support open timestamp inline (in nearest embed within same list/heading level, similar to [logseq](https://docs.logseq.com/#/page/626c0ab0-8f72-46a8-aaf6-057b7a6e6ada))
    - [ ]  respect native time stamp format if provider supports it
    - [ ] add native timestamp automatically when create timestamp link
    - [ ] timestamp link template
- [ ] document improvement
- [ ] [bundle](https://en.wikipedia.org/wiki/Bundle_(macOS)) format to store media meta, file, subtitle, thumbnails
    - folder note integration
    - support media url used as regular media file
    - timestamps in progress bar
    - bundle small files/urls into chapter for less impact on file access performance?
- [ ] embed height adjustment (styles setting?)
- [ ] skim through content and go back to original time: require thumbnail support
- [ ] UI to edit timestamp/time range: require thumbnail support
- [ ] open in media extended url scheme handler?

### CODE REVIEW

**Comment by Gr-Nobel** [comment]
How can i install it

**Comment by starsea** [comment]
Version 1.0.3 可用吗

**Comment by FlorianLiebhart** [comment]
When will this get merged?

**Comment by honkyphonk** [comment]
Any news to this? :-) Thank you!

**Pull request closed without merging**
